---
abstract: 'Safely and easily kill runaway processes'
author:
  - 'M. Nunberg <mnunberg@haskalah.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-ProcTerminator
no_index:
  directory:
    - t
    - inc
requires:
  POE: 0
  POE::Sugar::Attributes: 0.02
  Proc::Terminator: 0.03
  Test::More: 0
version: 0.01
